In [2]:
import math
import torch
import torch.nn as nn
import numpy as np
from model import GPT, GPTConfig
from context_free_grammar import CFG
import wandb

In [3]:
wandb.login()

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: aboitrea. Use `wandb login --relogin` to force relogin


True

In [4]:
cfg = CFG(L=3, ns=[1, 3, 9, 10], nr=[2, 2, 2], T=[8, 8, 8])
sentence_length = np.prod(cfg.T)

In [10]:
config = GPTConfig(vocab_size=cfg.ns[-1],
                   block_size=sentence_length-1,
                   n_embd=50, n_head=3,
                   n_layer=2,
                   batch_size=100)
m = GPT(config)
m = nn.DataParallel(m)
m = m.to(config.device)

number of parameters: 0.12M


In [11]:
 # print the number of parameters in the model
million_params = sum(p.numel() for p in m.parameters()) / 1e6
print(million_params, "M parameters")

0.1432 M parameters


### Define some useful functions for training/validation steps

In [6]:
# data loading = sample new sentences to fill-in the mini-batch
def get_batch(config: GPTConfig = GPTConfig()):
    data, _ = cfg.sample(config.batch_size)        # dropping labels (useless for the task)
    N = data.shape[0]                              # should be equal to config.batch_size
    data = data.view(N,sentence_length)            # flatten them to be (N,sentence_length)
    x = data[:, 0:sentence_length-1]               # (bsz,sentence_length-1)
    y = data[:, 1:sentence_length].contiguous()    # (bsz,sentence_length-1)
    x, y = x.to(config.device), y.to(config.device)
    return x, y

In [7]:
@torch.no_grad()
def estimate_loss(m, eval_iters=100):
    # This validation function samples a new batch of sentences and evaluates the loss of the model
    # Takes 20s for 100 sentences
    m.eval()
    losses = torch.zeros(eval_iters)
    for k in range(eval_iters):
        X, Y = get_batch()
        logits = m(X)
        loss = nn.functional.cross_entropy(logits.view(-1, logits.size(-1)), Y.view(-1), ignore_index=-1)
        losses[k] = loss.item()
    return losses.mean().item()

In [8]:
@torch.no_grad()
def eval_errors(m, n_gen=100, context_length=3):
    # for generating sentences from the model, we first sample real sentences from the grammar
    # then, the model is given the first 'context_length' symbols and asked to complete the sentence
    # Takes 40s for 100 sentences
    if isinstance(m, nn.DataParallel):
        m = m.module
    
    m.eval()
    context = cfg.sample(n_gen)[0].view(n_gen, sentence_length)[:,:context_length].to(config.device)
    gen_sentences = m.generate(context, max_new_tokens= sentence_length - context_length, temperature=0.1)

    # compute accuracy 
    gen_sentences = gen_sentences.view([n_gen] +  cfg.T).cpu()
    acc = cfg.frac_of_gramatically_correct_sentences(gen_sentences)  
    
    # compute per-level errors
    # a sentence can only be good at level i if it was good at all levels beteewn L and i+1
    correct_sentences = np.zeros(cfg.L)
    for sentence in gen_sentences:
        _, err = cfg.collapse_and_get_err(sentence)
        for i in range(len(err)-1,-1, -1):
            if err[i].sum() != 0:
                break
            else:
                correct_sentences[i] += 1
                
    return acc, np.array(correct_sentences) / n_gen * 100

In [9]:
sentence = cfg.sample(1)[0].view(1, sentence_length).to(config.device)
sentence[0,:8] = sentence[0,8:16]
sentence = sentence.view([1] +  cfg.T).cpu()
_, err = cfg.collapse_and_get_err(sentence)
print(err)
correct_sentences = np.zeros(cfg.L)
for i in range(len(err)-1,-1, -1):
    if err[i].sum() != 0:
        break
    else:
        correct_sentences[i] += 1
print(correct_sentences)

[tensor([0]), tensor([[1, 0, 0, 0, 0, 0, 0, 0]]), tensor([[[0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0]]])]
[0. 0. 1.]


### Learning rate scheduler

In [10]:
def get_lr(i,i_final):
    coeff = 0.5 * (1.0 + math.cos(math.pi * i/i_final)) # decays from 1 to 0 
    return min_lr + coeff * (max_lr - min_lr)

### Training parameters

In [11]:
# adamw optimizer
max_lr = 6e-4 # max learning rate
min_lr = max_lr/10
decay_lr = True

weight_decay = 1e-1
beta1 = 0.9
beta2 = 0.95
grad_clip = 1.0 # clip gradients at this value, or disable if == 0.0

optimizer = m.module.configure_optimizers(weight_decay, max_lr, (beta1, beta2), device_type='cuda')

num decayed parameter tensors: 26, with 142,850 parameters
num non-decayed parameter tensors: 7, with 350 parameters


In [17]:
training_parameters = {'num_epoch': 200,
                       'batches_per_epoch': 50,
                       'eval_iters': 100,
                       'quality_metric_iters': 100,
                       'learning_rate': 6e-4,
                       'architecture': f'GPT {million_params:.1f}M',
                       'model': config,
                       'grammar': cfg.__dict__}

In [18]:
training_parameters

{'num_epoch': 200,
 'batches_per_epoch': 50,
 'eval_iters': 100,
 'quality_metric_iters': 100,
 'learning_rate': 0.0006,
 'architecture': 'GPT 0.1M',
 'grammar': {'ns': [1, 3, 9, 10],
  'nr': [2, 2, 2],
  'T': [8, 8, 8],
  'L': 3,
  'rules': [tensor([[[2, 1, 1, 0, 0, 0, 0, 2],
            [2, 1, 2, 0, 0, 0, 2, 1]]]),
   tensor([[[7, 4, 0, 4, 5, 4, 8, 2],
            [8, 0, 7, 2, 0, 8, 3, 6]],
   
           [[4, 8, 0, 5, 7, 0, 4, 0],
            [2, 6, 6, 4, 8, 8, 5, 5]],
   
           [[6, 7, 7, 2, 2, 1, 5, 5],
            [3, 5, 2, 6, 3, 4, 2, 3]]]),
   tensor([[[6, 4, 5, 9, 5, 1, 1, 9],
            [9, 7, 4, 7, 6, 1, 1, 1]],
   
           [[1, 4, 9, 4, 0, 7, 8, 2],
            [8, 7, 2, 0, 3, 4, 4, 8]],
   
           [[6, 9, 2, 1, 3, 5, 1, 6],
            [4, 7, 0, 2, 7, 7, 1, 4]],
   
           [[3, 1, 6, 5, 1, 3, 0, 9],
            [4, 2, 4, 1, 1, 6, 4, 4]],
   
           [[1, 5, 6, 1, 5, 5, 5, 5],
            [0, 2, 3, 5, 7, 8, 7, 7]],
   
           [[6, 5, 5, 7, 8, 7, 1, 9

In [13]:
# Training loop
# 1 epoch (train + val) is 1m20s
def train(m):
    print(f'One epoch is {training_parameters["batches_per_epoch"]} steps,' +
    f'validation loss is computed at the end of every epoch and quality metric is '+
    f'averaged over {training_parameters["quality_metric_iters"]} sentences')
    print(f'Will run for {training_parameters["num_epoch"]} epochs')
    total_num_iter = training_parameters['num_epoch'] * training_parameters['batches_per_epoch']
    for epoch in range(training_parameters['num_epoch']):
        train_loss_sum = .0
        m.train()
        # determine and set the learning rate for this epoch
        lr = get_lr(epoch, training_parameters['num_epoch']) if decay_lr else max_lr
        for param_group in optimizer.param_groups:
            param_group['lr'] = lr
        for iter in range(training_parameters['batches_per_epoch']):
            # sample a batch of data
            xb, yb = get_batch(config)
            # evaluate the loss
            optimizer.zero_grad()
            logits = m(xb)
            loss = nn.functional.cross_entropy(logits.view(-1, logits.size(-1)), yb.view(-1), ignore_index=-1)
            train_loss_sum += loss.item()
            loss.backward()
            optimizer.step()
        # evaluate the loss on newly generated sentences at the end of every epoch
        train_loss = train_loss_sum / config.batch_size
        val_loss = estimate_loss(m, training_parameters["eval_iters"])
        acc, errors = eval_errors(m, training_parameters['quality_metric_iters'], context_length=3)
        log_dict = {"nb sentences seen": (epoch+1)*training_parameters['batches_per_epoch']*config.batch_size,
                    "val_loss": val_loss,
                    "train_loss": train_loss,
                    "accuracy": acc * 100,
                    "learning_rate": optimizer.param_groups[0]["lr"]}
        for i,err in enumerate(errors):
            log_dict[f'% of correct sentences at level {i}'] = err
        
        if epoch % 10 == 0:
            formatted_stats = ', '.join(f'{key}: {value}' for key, value in log_dict.items())
            print(formatted_stats)
        wandb.log(log_dict)

In [14]:
wandb.init(project='CFG-Experiments', config=training_parameters, name=f'h{config.n_head} l{config.n_layer} embed={config.n_embd} {million_params:.1f}M temp=0.1')
wandb.watch(m, log='all')

train(m)
wandb.finish()

One epoch is 50 steps,validation loss is computed at the end of every epoch and quality metric is averaged over 100 sentences
Will run for 200 epochs
nb sentences seen: 5000, val_loss: 1.519534707069397, train_loss: 0.9341575396060944, accuracy: 0.0, learning_rate: 0.0005999999999999998, % of correct sentences at level 0: 0.0, % of correct sentences at level 1: 0.0, % of correct sentences at level 2: 0.0
nb sentences seen: 55000, val_loss: 0.25505539774894714, train_loss: 0.13083992421627044, accuracy: 0.0, learning_rate: 0.0005966758519606872, % of correct sentences at level 0: 0.0, % of correct sentences at level 1: 0.0, % of correct sentences at level 2: 0.0
nb sentences seen: 105000, val_loss: 0.1673106998205185, train_loss: 0.08611028745770455, accuracy: 0.0, learning_rate: 0.0005867852593996914, % of correct sentences at level 0: 0.0, % of correct sentences at level 1: 0.0, % of correct sentences at level 2: 0.0
nb sentences seen: 155000, val_loss: 0.10842473804950714, train_loss